### ISSUE TITLE
Firebase Android Integration

### ISSUE THREAD

**Issue by bkvie** [janoodleFTW/timy-messenger#16]
Could you update the firbase integration for Andriod. Trying to get it to run threw up numerous errors.

**Comment by miquelbeltran** [comment]
Can you provide more info? What kind of errors do you get?

**Comment by bkvie** [comment]
after fixing dependency issues I am now left with:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'de.janoodle.circlesApp.debug'

```

Obviously made sure the package names match. Sure the firebase integration/Android integration is as straigh forward as the iOS one?

**Comment by miquelbeltran** [comment]
What's your app id on Firebase?

**Comment by miquelbeltran** [comment]
For the issue you are facing, seems that your Firebase app id and the app id are not the same, see this answer on StackOverflow for a solution: https://stackoverflow.com/questions/34990479/no-matching-client-found-for-package-name-google-analytics-multiple-productf

Also, you say "after fixing dependency issues". Could you give some examples? We haven't seen any problems like that.

**Comment by miquelbeltran** [comment]
The dependency issues you got are like these? https://github.com/janoodleFTW/timy-messenger/issues/20 (see issue #20)
