### ISSUE TITLE
Step-by-step Android Firebase setup

### ISSUE THREAD

**Issue by miquelbeltran** [janoodleFTW/timy-messenger#19]
Seen that some devs are having issues with the Android setup https://github.com/janoodleFTW/timy-messenger/issues/16

I'd love is someone can write a step-by-step documentation on the `/android/README.md` file on how to register the Timy Messenger app on Firebase:

- Add the app on Firebase.
- Be sure that the app id is correct
- Where to put the google services json.
- Plus adding some sort of troubleshooting / FAQ.

**Comment by sduduzog** [comment]
This is interesting, it would most likely require a demo app also

**Comment by miquelbeltran** [comment]
It is for the Timy Messenger. The goal is to have a documented step by step guide for new developers to know how to setup Firebase for this app (the Timy Messenger). It does not require a demo app.

**Comment by sduduzog** [comment]
I'll give it a shot

**Comment by sduduzog** [comment]
@miquelbeltran I'm having build issues, and it's not yet related with firebase setup, looks like dependency issues which I might try to resolve by attempting to migrate android  to andoidx

**Comment by miquelbeltran** [comment]
Please report a separated issue, and include your `flutter doctor` output too because I guess we have different Flutter versions.

**Comment by sduduzog** [comment]
I think I've figure out why I had issues, I'm moving on with the work. I'll try to document my hurdle also @miquelbeltran

**Comment by miquelbeltran** [comment]
btw, I created this issue: https://github.com/janoodleFTW/timy-messenger/issues/20 it is probably what you saw, so if you had the same issue, maybe you can also provide a solution to it :)

**Comment by miquelbeltran** [comment]
Fixed.
