### ISSUE TITLE
Blank/white screen after login

### ISSUE THREAD

**Issue by xxxcrow** [janoodleFTW/timy-messenger#23]
Can login successfully, but after that see only the blank page, with debug mark
What's wrong? 
Flutter doctor- no issues
A lot of errors during the compilation
But the login page was great, why not further? 😭

**Comment by miquelbeltran** [comment]
Please read the instructions in the README.md, you need to create all the necessary groups/users in Firestore

**Comment by xxxcrow** [comment]
![image](https://user-images.githubusercontent.com/24483751/66703780-68981d00-ed40-11e9-977e-ac8d5b122dd0.png)
![image](https://user-images.githubusercontent.com/24483751/66703784-73eb4880-ed40-11e9-8d0d-5bbe89a6e5f8.png)
can you check please, because i thought i added everything correctly 😢

**Comment by xxxcrow** [comment]
> Please read the instructions in the README.md, you need to create all the necessary groups/users in Firestore

yeah, yeah, i changed location to asia, because in my case it is really impractical to use eroupe 😅

**Comment by miquelbeltran** [comment]
I see that the README.md is incomplete.

Each 'user' document also needs to have a field `joinedGroups` with an array of the group ids, as it is generated in the script https://github.com/janoodleFTW/timy-messenger/blob/master/firebase/scripts/group-create.js

I will reopen this, let me know if that helps.

**Comment by miquelbeltran** [comment]
I will also create a new Issue pointing that this step is missing.

**Comment by xxxcrow** [comment]
<img width="652" alt="Annotation 2019-10-13 103808" src="https://user-images.githubusercontent.com/24483751/66710585-d1fe4700-eda5-11e9-902c-b8dcb241239a.png">
like this? 😥 (doesn't work, or i've done something wrong besides this 😔)

**Comment by miquelbeltran** [comment]
the 'id' should be the group document id, in your case `b6qH...`etc.

**Comment by miquelbeltran** [comment]
Another thing, you `channels` collections be a subcollection of the `group` you have created, and not a top level collections. Please check the updated README.md.

I verified the whole setup now, please check the instructions again and compare the screenshots in the README.md to your database.
