### ISSUE TITLE
Doesn't work after reloading "No matching client found for package name 'de.janoodle.circlesApp'"

### ISSUE THREAD

**Issue by xxxcrow** [janoodleFTW/timy-messenger#26]
**Describe the bug**

I reloaded the project (actually updated, but after that it became unworking)

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
No matching client found for package name 'de.janoodle.circlesApp'

(yeah, yeah, it seems like the problem is in google-services.json, but...
I cannot understand where it goes from)
(because I tried everything, changing apps in firebase, editing the config, changing all the names in the project, DELETING the project in firebase)

**To Reproduce**

1. Clone the project
2. Set up firebase
3. Put JSON where it should be
4. Debug

**Expected behavior**

Run the project :D

**Device Information:**

 - Device: Xiaomi 9
 - OS: Android 9
 
**Flutter Information**
 ```
 [√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18990.1], locale en-US)
    • Flutter version 1.9.1+hotfix.4 at C:\src\flutter\flutter
    • Framework revision cc949a8e8b (2 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\****\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.39.1)
    • VS Code at C:\Users\****\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (1 available)
    • MI 9 • cbfecdcd • android-arm64 • Android 9 (API 28)

• No issues found!
 ```
**Logs**

```
Launching lib\main.dart on MI 9 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'de.janoodle.circlesApp'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

**Additional context**

Maybe i'm just a dumb, or cannot find what changed 
Sorry for disturbing again, but i'm confused 😥 (especially after the new changes)

**Comment by miquelbeltran** [comment]
> No matching client found for package name 'de.janoodle.circlesApp'

This means that the application id does not match the Firebase app id.

You either need to change the Firebase app id to 'de.janoodle.circlesApp' and download again the google-services.json OR change the application id on the `android/build.gradle` to be the same you have on Firebase.

**Comment by miquelbeltran** [comment]
Most likely change the line 

```
        applicationId "de.janoodle.circlesApp"
```
to 
```
        applicationId "de.janoodle.circlesApp.debug"
```

**Comment by xxxcrow** [comment]
> > No matching client found for package name 'de.janoodle.circlesApp'
> 
> This means that the application id does not match the Firebase app id.
> 
> You either need to change the Firebase app id to 'de.janoodle.circlesApp' and download again the google-services.json OR change the application id on the `android/build.gradle` to be the same you have on Firebase.

the problem is that I TRIED IT :O
it's obvious that the names have to match
BUT, i try to debug on android, the clean project with new apps in firebase 
it seems like it cached somewhere, sorry for disturbing i just didn't expect this kind of problem
(or something wrong with firebase console, because when i delete all the apps and create only one, it still shows information about the other)

**Comment by xxxcrow** [comment]
ok, it's really strange, i checked everything again and again 
Error:
`* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'de.janoodle.circlesApp'
`
google-services.json:
`"client_info": {
        "mobilesdk_app_id": "123123123123123123123",
        "android_client_info": {
          "package_name": "com.example.circles_app"
....
another things
....
              "client_id": "123123123123123123123",
              "client_type": 2,
              "ios_info": {
                "bundle_id": "de.janoodle.circlesApp.debug"
`
My Apps: (i know, no "debug", i did with them before, no i just add that the error asks me)
<img width="311" alt="Annotation 2019-10-15 223536" src="https://user-images.githubusercontent.com/24483751/66846536-2703ae00-ef9c-11e9-8c91-e5c9831af939.png">

**Comment by xxxcrow** [comment]
ah, and another thing.
the json file was created BEFORE creating the ios app!!!

**Comment by xxxcrow** [comment]
<img width="303" alt="Annotation 2019-10-15 233218" src="https://user-images.githubusercontent.com/24483751/66851017-1b1bea00-efa4-11e9-9ea3-87921f6e71a4.png">
the situation hasn't changed

**Comment by xxxcrow** [comment]
i'm an idiot... 
i checked not that gradle.build
and took the name from the manifest...

**Comment by RoyalCoder88** [comment]
how did you fix the issue? I have the same problem tried a lot of things and nothing

**Comment by moustaouiSalaheddine** [comment]
if you have google-services.json change your package in inside google-services.json
if work : generate a new google-services.json
