### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [janoodleFTW/timy-messenger#28]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by fheinfling** [comment]
Thank you @mansya it's very kind of you! I'm afraid this app actually has an original design including an icon. Hope you can understand that. Thanks a bunch!
