### ISSUE TITLE
ERROR : imagepicker plugins 

### ISSUE THREAD

**Issue by MaTaDoRcpe** [janoodleFTW/timy-messenger#36]
> > Launching lib\main.dart on Android SDK built for x86 in debug mode...
> Initializing gradle...
> Resolving dependencies...
> [{"event":"app.progress","params":{"appId":"6b3cb832-c943-46f5-8b92-5143851d66e4","id":"2","progressId":null,"message":"Running Gradle task 'assembleDebug'..."}}]Running Gradle task 'assembleDebug'...
> 
> registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
> registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
> registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
> D:\mobileProject\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.12+1\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerDelegate.java:15: error: package android.support.annotation does not exist
> import android.support.annotation.VisibleForTesting;
>                                  ^
> D:\mobileProject\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.12+1\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerDelegate.java:16: error: cannot find symbol
> import android.support.v4.app.ActivityCompat;
>                              ^
>   symbol:   class ActivityCompat
>   location: package android.support.v4.app
> D:\mobileProject\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.12+1\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerDelegate.java:17: error: package android.support.v4.content does not exist
> import android.support.v4.content.FileProvider;
>                                  ^
> D:\mobileProject\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.12+1\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerFileProvider.java:3: error: package android.support.v4.content does not exist
> import android.support.v4.content.FileProvider;
>                                  ^
> D:\mobileProject\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.12+1\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerFileProvider.java:10: error: cannot find symbol
> public class ImagePickerFileProvider extends FileProvider {}
>                                              ^
>   symbol: class FileProvider
> D:\mobileProject\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.12+1\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerPlugin.java:8: error: package android.support.annotation does not exist
> import android.support.annotation.VisibleForTesting;
>                                  ^
> D:\mobileProject\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.12+1\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerDelegate.java:68: error: cannot find symbol
>   @VisibleForTesting static final int REQUEST_CODE_CHOOSE_IMAGE_FROM_GALLERY = 2342;
>    ^
>   symbol:   class VisibleForTesting
>   location: class ImagePickerDelegate
> D:\mobileProject\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.12+1\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerDelegate.java:69: error: cannot find symbol
>   @VisibleForTesting static final int REQUEST_CODE_TAKE_IMAGE_WITH_CAMERA = 2343;
>    ^
>   symbol:   class VisibleForTesting
>   location: class ImagePickerDelegate
> D:\mobileProject\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.12+1\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerDelegate.java:70: error: cannot find symbol
>   @VisibleForTesting static final int REQUEST_EXTERNAL_IMAGE_STORAGE_PERMISSION = 2344;
>    ^
>   symbol:   class VisibleForTesting
>   location: class ImagePickerDelegate
> D:\mobileProject\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.12+1\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerDelegate.java:71: error: cannot find symbol
>   @VisibleForTesting static final int REQUEST_CAMERA_IMAGE_PERMISSION = 2345;
>    ^
>   symbol:   class VisibleForTesting
>   location: class ImagePickerDelegate
> D:\mobileProject\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.12+1\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerDelegate.java:72: error: cannot find symbol
>   @VisibleForTesting static final int REQUEST_CODE_CHOOSE_VIDEO_FROM_GALLERY = 2352;
>    ^
>   symbol:   class VisibleForTesting
>   location: class ImagePickerDelegate
> D:\mobileProject\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.12+1\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerDelegate.java:73: error: cannot find symbol
>   @VisibleForTesting static final int REQUEST_CODE_TAKE_VIDEO_WITH_CAMERA = 2353;
>    ^
>   symbol:   class VisibleForTesting
>   location: class ImagePickerDelegate
> D:\mobileProject\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.12+1\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerDelegate.java:74: error: cannot find symbol
>   @VisibleForTesting static final int REQUEST_EXTERNAL_VIDEO_STORAGE_PERMISSION = 2354;
>    ^
>   symbol:   class VisibleForTesting
>   location: class ImagePickerDelegate
> D:\mobileProject\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.12+1\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerDelegate.java:75: error: cannot find symbol
>   @VisibleForTesting static final int REQUEST_CAMERA_VIDEO_PERMISSION = 2355;
>    ^
>   symbol:   class VisibleForTesting
>   location: class ImagePickerDelegate
> D:\mobileProject\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.12+1\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerDelegate.java:77: error: cannot find symbol
>   @VisibleForTesting final String fileProviderName;
>    ^
>   symbol:   class VisibleForTesting
>   location: class ImagePickerDelegate
> D:\mobileProject\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.12+1\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerDelegate.java:164: error: cannot find symbol
>   @VisibleForTesting
>    ^
>   symbol:   class VisibleForTesting
>   location: class ImagePickerDelegate
> D:\mobileProject\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.12+1\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerPlugin.java:40: error: cannot find symbol
>   @VisibleForTesting
>    ^
>   symbol:   class VisibleForTesting
>   location: class ImagePickerPlugin
> D:\mobileProject\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.12+1\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerDelegate.java:122: error: cannot find symbol
>             return ActivityCompat.checkSelfPermission(activity, permissionName)
>                    ^
>   symbol: variable ActivityCompat
> D:\mobileProject\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.12+1\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerDelegate.java:128: error: cannot find symbol
>             ActivityCompat.requestPermissions(activity, new String[] {permissionName}, requestCode);
>             ^
>   symbol: variable ActivityCompat
> D:\mobileProject\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.12+1\android\src\main\java\io\flutter\plugins\imagepicker\ImagePickerDelegate.java:140: error: cannot find symbol
>             return FileProvider.getUriForFile(activity, fileProviderName, file);
>                    ^
>   symbol: variable FileProvider
> 20 errors
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':image_picker:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2s
> AndroidX incompatibilities may have caused this build to fail. See https://goo.gl/CP92wY.
> Finished with error: Gradle task assembleDebug failed with exit code 1
>

**Comment by senorcodecat** [comment]
Having the same issue. This was closed but what's the fix?

**Comment by MaTaDoRcpe** [comment]
> Having the same issue. This was closed but what's the fix?

The above error was caused by [AndroidX], I fix it with [https://goo.gl/CP92wY](https://goo.gl/CP92wY)
