### ISSUE TITLE
Cannot build app

### ISSUE THREAD

**Issue by xJon** [janoodleFTW/timy-messenger#41]
I've followed step by step the instructions in the readme file, yet after a few hours of troubleshooting I still can't seem to build the app properly.
Not modifying anything (and using the recommended Flutter version) I run into this issue:
```
flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-3.1.5\android\src\main\java\io\flutter\plugins\firebase\storage\FirebaseStoragePlugin.java:59: error: cannot find symbol
    onAttachedToEngine(binding.getApplicationContext(), binding.getBinaryMessenger());
                                                               ^
  symbol:   method getBinaryMessenger()
  location: variable binding of type FlutterPluginBinding
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':firebase_storage:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```
Trying to update dependencies caused other issues.
Any tips?
Thank you!

**Comment by xJon** [comment]
This issue was fixed by simply trying with a new project, and making sure even harder to not accidentally update Flutter or any other package.

**Comment by Szintai** [comment]
What other packages besides the Flutter? I have the same issue.
